In [1]:
import pandas as pd
import numpy as np

In [2]:
messages = pd.read_csv(r"C:\Users\des\Desktop\ALL AI\Ai\spam.csv", encoding='latin1')

In [3]:
messages

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
messages.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace = True,axis=1)

In [5]:
messages.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\des\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [8]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^A-Za-z]',' ',messages['v2'][i]) ## to remove special characters
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word,pos='v') for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',


In [10]:
## create the Bag Of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000) ##taking 2000 words which are having the maximum frequency across the corpus


In [11]:
##np.set_printoptions(threshold=np.inf) ## to print all the values of the array
X=cv.fit_transform(corpus).toarray()

In [12]:
X ## this is with respect to , normal BOW , where we will getting count of the words

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
##NOW FOR BINARY BOW
cv_binary = CountVectorizer(max_features = 200,binary=True) ## took less features just fir sake of example

In [14]:
Y = cv_binary.fit_transform(corpus).toarray()

In [15]:
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
## TO SEE THE TOP 200 WORDS
cv_binary.vocabulary_

{'go': 647,
 'point': 1276,
 'crazy': 351,
 'available': 110,
 'bugis': 210,
 'great': 663,
 'world': 1947,
 'la': 882,
 'cine': 284,
 'get': 634,
 'wat': 1888,
 'ok': 1170,
 'lar': 890,
 'joke': 847,
 'wif': 1922,
 'oni': 1178,
 'free': 582,
 'entry': 481,
 'wkly': 1937,
 'comp': 312,
 'win': 1926,
 'fa': 515,
 'cup': 362,
 'final': 547,
 'tkts': 1759,
 'st': 1623,
 'may': 1024,
 'text': 1721,
 'receive': 1383,
 'question': 1347,
 'std': 1633,
 'txt': 1805,
 'rate': 1366,
 'apply': 81,
 'dun': 449,
 'say': 1460,
 'early': 453,
 'already': 56,
 'nah': 1112,
 'think': 1736,
 'usf': 1845,
 'live': 944,
 'around': 94,
 'though': 1741,
 'freemsg': 584,
 'hey': 711,
 'darling': 380,
 'week': 1903,
 'word': 1944,
 'back': 121,
 'like': 933,
 'fun': 605,
 'still': 1637,
 'tb': 1702,
 'xxx': 1971,
 'send': 1488,
 'rcv': 1369,
 'even': 491,
 'brother': 203,
 'speak': 1610,
 'treat': 1787,
 'per': 1228,
 'request': 1409,
 'melle': 1036,
 'oru': 1195,
 'set': 1499,
 'callertune': 228,
 'callers':

### N-GRAMS

In [26]:
## create the Bag Of Words with N-Grams
from sklearn.feature_extraction.text import CountVectorizer
cv_unigram = CountVectorizer(max_features=100,ngram_range=(1,1))##unigram - by default
cv_unigram.fit_transform(corpus).toarray()
cv_bigram = CountVectorizer(max_features=100,ngram_range=(2,2))##unigram to trigram
cv_bigram.fit_transform(corpus).toarray()
cv_trigram = CountVectorizer(max_features=100,ngram_range=(3,3))##bigram to trigram
cv_trigram.fit_transform(corpus).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
print(cv.vocabulary_)


{'go': 647, 'point': 1276, 'crazy': 351, 'available': 110, 'bugis': 210, 'great': 663, 'world': 1947, 'la': 882, 'cine': 284, 'get': 634, 'wat': 1888, 'ok': 1170, 'lar': 890, 'joke': 847, 'wif': 1922, 'oni': 1178, 'free': 582, 'entry': 481, 'wkly': 1937, 'comp': 312, 'win': 1926, 'fa': 515, 'cup': 362, 'final': 547, 'tkts': 1759, 'st': 1623, 'may': 1024, 'text': 1721, 'receive': 1383, 'question': 1347, 'std': 1633, 'txt': 1805, 'rate': 1366, 'apply': 81, 'dun': 449, 'say': 1460, 'early': 453, 'already': 56, 'nah': 1112, 'think': 1736, 'usf': 1845, 'live': 944, 'around': 94, 'though': 1741, 'freemsg': 584, 'hey': 711, 'darling': 380, 'week': 1903, 'word': 1944, 'back': 121, 'like': 933, 'fun': 605, 'still': 1637, 'tb': 1702, 'xxx': 1971, 'send': 1488, 'rcv': 1369, 'even': 491, 'brother': 203, 'speak': 1610, 'treat': 1787, 'per': 1228, 'request': 1409, 'melle': 1036, 'oru': 1195, 'set': 1499, 'callertune': 228, 'callers': 227, 'press': 1308, 'copy': 337, 'friends': 592, 'winner': 1929, '

In [28]:
print(cv_bigram.vocabulary_)


{'free entry': 31, 'claim call': 15, 'call claim': 3, 'free call': 30, 'chance win': 14, 'txt word': 88, 'let know': 53, 'go home': 35, 'mobile free': 59, 'please call': 67, 'lt gt': 57, 'miss call': 58, 'want go': 97, 'like lt': 54, 'sorry call': 80, 'call later': 8, 'ur award': 89, 'hi hi': 46, 'come back': 20, 'call customer': 4, 'customer service': 22, 'cash prize': 13, 'try contact': 85, 'draw show': 27, 'show prize': 79, 'prize guarantee': 73, 'guarantee call': 43, 'valid hrs': 95, 'select receive': 76, 'private account': 71, 'account statement': 0, 'statement show': 81, 'call identifier': 5, 'identifier code': 49, 'code expire': 19, 'urgent mobile': 94, 'call landline': 7, 'wat time': 98, 'ur mob': 92, 'go get': 34, 'gud ni': 44, 'send stop': 78, 'ur mobile': 93, 'get back': 33, 'co uk': 18, 'nice day': 64, 'lt decimal': 56, 'decimal gt': 24, 'txt nokia': 86, 'good morning': 38, 'good night': 39, 'reply call': 75, 'po box': 69, 'last night': 52, 'camera phone': 12, 'pick phone':

In [29]:
print(cv_trigram.vocabulary_)

{'like lt gt': 42, 'sorry call later': 81, 'please call customer': 67, 'call customer service': 6, 'customer service representative': 21, 'guarantee cash prize': 33, 'draw show prize': 22, 'show prize guarantee': 79, 'prize guarantee call': 72, 'specially select receive': 83, 'speak live operator': 82, 'live operator claim': 44, 'private account statement': 70, 'account statement show': 0, 'call identifier code': 7, 'identifier code expire': 39, 'bonus caller prize': 4, 'select receive award': 78, 'match please call': 55, 'urgent try contact': 97, 'lt decimal gt': 46, 'secret admirer look': 77, 'admirer look make': 1, 'look make contact': 45, 'make contact find': 54, 'contact find reveal': 19, 'find reveal think': 27, 'reveal think ur': 75, 'think ur special': 87, 'ur special call': 94, 'draw txt music': 23, 'www ldew com': 99, 'anytime network mins': 2, 'camcorder reply call': 12, 'cant pick phone': 13, 'pick phone right': 66, 'phone right pls': 65, 'right pls send': 76, 'pls send mes