In [1]:
import gensim

In [2]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

In [3]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
import pandas as pd
import numpy as np


In [5]:
messages = pd.read_csv(r"C:\Users\des\Desktop\ALL AI\Ai\spam.csv", encoding='latin1')
messages.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace = True,axis=1)

In [6]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\des\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [30]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^A-Za-z]',' ',messages['v2'][i]) ## to remove special characters
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word,pos='v') for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [33]:
len([(i,j, k) for i, j, k in zip(map(len, corpus), corpus, messages['v2']) if i < 1]) ## these 8 are the messages that get lost in corpus creation because of specialized words its contiaining
## since some of the data points will be lost during training , we will have to make sure that Y variable at time of model training 
## should also have exactly same no of data points

8

In [9]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',


In [10]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess ## convert a document into list of lowercase tokens , ignoring tokens that are too short or too long

In [13]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))


In [14]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'get',
  'amore',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'callers',
  'press',
  'copy',
  'friends',
  'callertune'],
 ['winner',
  'value',
  'network',
  'customer',
  'select',
  'receivea',
  'p

In [15]:
##Lets train our model from scratch
model = gensim.models.Word2Vec(words)

In [16]:
model

In [17]:
## to get all the vocabulary
model.wv.index_to_key

['get',
 'call',
 'go',
 'ur',
 'come',
 'gt',
 'lt',
 'ok',
 'free',
 'know',
 'send',
 'like',
 'time',
 'want',
 'love',
 'good',
 'day',
 'say',
 'think',
 'tell',
 'take',
 'text',
 'need',
 'see',
 'txt',
 'make',
 'one',
 'stop',
 'home',
 'reply',
 'lor',
 'today',
 'sorry',
 'still',
 'back',
 'da',
 'dont',
 'mobile',
 'phone',
 'meet',
 'please',
 'hi',
 'new',
 'later',
 'work',
 'pls',
 'ask',
 'miss',
 'week',
 'give',
 'message',
 'dear',
 'wait',
 'well',
 'leave',
 'much',
 'great',
 'night',
 'claim',
 'oh',
 'hope',
 'try',
 'msg',
 'hey',
 'number',
 'wat',
 'happy',
 'thank',
 'way',
 'yes',
 'find',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'tomorrow',
 'win',
 'even',
 'pick',
 'already',
 'tone',
 'cash',
 'sleep',
 'yeah',
 'really',
 'amp',
 'im',
 'keep',
 'life',
 'buy',
 'last',
 'morning',
 'babe',
 'care',
 'service',
 'com',
 'would',
 'cos',
 'uk',
 'contact',
 'nokia',
 'also',
 'lol',
 'anything',
 'use',
 'every',
 'wish',
 'start',
 'look',
 'su

In [18]:
model.corpus_count

5564

In [19]:
## similar words
model.wv.similar_by_word('kid')

[('friends', 0.998315691947937),
 ('today', 0.9982433319091797),
 ('really', 0.9982126951217651),
 ('drive', 0.9981939792633057),
 ('much', 0.9981454610824585),
 ('know', 0.9981372952461243),
 ('worry', 0.9981288313865662),
 ('work', 0.9981286525726318),
 ('da', 0.9981273412704468),
 ('stuff', 0.9981170892715454)]

In [20]:
model.wv['kid']

array([-9.6551459e-03,  1.4124067e-01,  4.5352492e-02, -1.1660997e-02,
        3.7826765e-02, -2.3486707e-01,  7.4703939e-02,  2.7442423e-01,
       -8.3304130e-02, -8.0493562e-02, -7.8010723e-02, -1.8985815e-01,
        5.0325864e-03,  3.9934646e-03,  5.4770552e-02, -6.6692293e-02,
        1.5080649e-02, -1.0513329e-01,  1.6000945e-02, -2.5219995e-01,
        8.9017875e-02,  5.2076850e-02,  5.8344167e-02, -6.9183081e-02,
       -5.7091087e-02,  2.0457193e-02, -1.4076646e-01, -1.6267551e-01,
       -6.7420356e-02,  1.5934898e-02,  1.3621905e-01,  3.6459826e-02,
        3.3067122e-02, -2.6497707e-02, -8.3191164e-02,  1.7878570e-01,
        2.9077696e-02, -1.4195934e-01, -7.7716880e-02, -2.7692738e-01,
        8.7220790e-03, -8.1995040e-02, -1.1172986e-03,  7.4092825e-03,
        1.3687840e-01, -6.3972294e-02, -8.1158914e-02, -3.6770202e-02,
        3.5157997e-02,  4.6569664e-02,  9.0255171e-02, -6.7215621e-02,
        3.2859223e-03,  2.7209470e-02, -2.4496170e-02,  6.8834670e-02,
      

In [21]:
def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if vectors:  # avoid empty list
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size)  # or 300 if that's your vector size


In [22]:
!pip install tqdm 

In [23]:
from tqdm import tqdm

In [24]:
X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))
    

100%|████████████████████████████████████████████████████████████████████████████| 5564/5564 [00:01<00:00, 3903.73it/s]


In [25]:
X

[array([-0.00199446,  0.28370255,  0.07011963, -0.02586037,  0.06742564,
        -0.4402634 ,  0.15892673,  0.53122455, -0.18065618, -0.15569943,
        -0.15352267, -0.37630644, -0.00606093,  0.01515942,  0.09085644,
        -0.13394028,  0.02353056, -0.2186421 ,  0.02006263, -0.50325227,
         0.17073895,  0.10660491,  0.10546929, -0.13217156, -0.11571188,
         0.03353725, -0.26147014, -0.31042168, -0.1514387 ,  0.04953774,
         0.2497651 ,  0.06522202,  0.04534343, -0.06519751, -0.14388989,
         0.33117637,  0.05091712, -0.25829467, -0.13531543, -0.5315713 ,
         0.02855007, -0.14737329, -0.01451133,  0.03110036,  0.246595  ,
        -0.14188987, -0.14400323, -0.0584289 ,  0.0580266 ,  0.09932631,
         0.18746948, -0.13454357, -0.00501209,  0.04525493, -0.06850186,
         0.14322132,  0.14398941, -0.01393722, -0.314693  ,  0.09778491,
         0.05976953,  0.09156854, -0.04178021, -0.07150275, -0.31152543,
         0.08276242,  0.13761583,  0.18331757, -0.3

In [26]:
X = np.array(X)

In [36]:
X.shape

(5564, 100)

In [27]:
X[0]

array([-0.00199446,  0.28370255,  0.07011963, -0.02586037,  0.06742564,
       -0.44026339,  0.15892673,  0.53122455, -0.18065618, -0.15569943,
       -0.15352267, -0.37630644, -0.00606093,  0.01515942,  0.09085644,
       -0.13394028,  0.02353056, -0.2186421 ,  0.02006263, -0.50325227,
        0.17073895,  0.10660491,  0.10546929, -0.13217156, -0.11571188,
        0.03353725, -0.26147014, -0.31042168, -0.1514387 ,  0.04953774,
        0.2497651 ,  0.06522202,  0.04534343, -0.06519751, -0.14388989,
        0.33117637,  0.05091712, -0.25829467, -0.13531543, -0.53157133,
        0.02855007, -0.14737329, -0.01451133,  0.03110036,  0.246595  ,
       -0.14188987, -0.14400323, -0.0584289 ,  0.0580266 ,  0.09932631,
        0.18746948, -0.13454357, -0.00501209,  0.04525493, -0.06850186,
        0.14322132,  0.14398941, -0.01393722, -0.314693  ,  0.09778491,
        0.05976953,  0.09156854, -0.04178021, -0.07150275, -0.31152543,
        0.08276242,  0.13761583,  0.18331757, -0.37255228,  0.21

In [28]:
## dependent features 
Y = pd.get_dummies(messages['v1'])
Y = Y.iloc[:,0].values

In [37]:
Y.shape

(5572,)

In [40]:
## making Y equal to the number of data points of X
Y = messages[list(map(lambda x:len(x)>0 , corpus))]
Y = pd.get_dummies(Y['v1'])
Y = Y.iloc[:,0].values

In [41]:
Y.shape

(5564,)

In [42]:
## now the final indpendent feature
df = pd.DataFrame()
for i in range(0,len(X)):
    df = df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

C:\Users\des\AppData\Local\Temp\ipykernel_25976\2068533765.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)


In [44]:
df.shape

(5564, 100)

In [47]:
df['output'] = Y

In [49]:
df.dropna(inplace=True)

In [48]:
df.head()

0         1         2         3         4         5         6  \
0 -0.001994  0.283703  0.070120 -0.025860  0.067426 -0.440263  0.158927   
1  0.000847  0.261141  0.065485 -0.019600  0.060036 -0.397462  0.147693   
2 -0.003402  0.308068  0.073594 -0.024825  0.073246 -0.463480  0.177488   
3  0.000866  0.407933  0.102345 -0.042657  0.098858 -0.624233  0.227986   
4 -0.000375  0.309638  0.074278 -0.034910  0.078762 -0.476992  0.173902   

          7         8         9  ...        91        92        93        94  \
0  0.531225 -0.180656 -0.155699  ...  0.125255 -0.037796  0.076040  0.483781   
1  0.487089 -0.162773 -0.142726  ...  0.113302 -0.032390  0.066657  0.442366   
2  0.557613 -0.193408 -0.163369  ...  0.124469 -0.038747  0.079651  0.509601   
3  0.764776 -0.260667 -0.222658  ...  0.181995 -0.046211  0.114140  0.694055   
4  0.582231 -0.201737 -0.168347  ...  0.135681 -0.038804  0.084780  0.532802   

         95        96        97        98        99  output  
0  0.233431  0.106693 -0.263836  0.072191 -0.111178       1  
1  0.212833  0.099147 -0.240033  0.069883 -0.099563       1  
2  0.250228  0.113257 -0.280321  0.071815 -0.128136       0  
3  0.329327  0.150417 -0.377397  0.113152 -0.160958       1  
4  0.256018  0.121120 -0.289508  0.086872 -0.123236       1  

[5 rows x 101 columns]

In [50]:
X = df.drop('output',axis=1) ## finally

In [52]:
Y = df['output']

In [53]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [54]:
from sklearn.ensemble import RandomForestClassifier


In [55]:
classifier = RandomForestClassifier()

In [56]:
classifier.fit(X_train,Y_train)

RandomForestClassifier()

In [62]:
Y_test_pred = classifier.predict(X_test)
Y_train_pred = classifier.predict(X_train)

In [58]:
from sklearn.metrics import accuracy_score, classification_report

In [64]:
accuracy_score(Y_test,Y_test_pred),accuracy_score(Y_train,Y_train_pred)

(0.9748427672955975, 0.9995506627724107)

In [61]:
print(classification_report(Y_test,Y_test_pred))

              precision    recall  f1-score   support

           0       0.93      0.87      0.90       142
           1       0.98      0.99      0.99       971

    accuracy                           0.97      1113
   macro avg       0.95      0.93      0.94      1113
weighted avg       0.97      0.97      0.97      1113

